### ISSUE TITLE
Using a simplified approach and not a database

### ISSUE THREAD

**Issue by borioan** [jalilverdiyev/ChatAppWpf#1]
Hello! ChatAppWpf is a very good application that I am using as a learning project. Unfortunately it uses a database which, in my case is not necessary. I would like to be able to use something less complicated, where I have a limited and known number of clients that allows adding or deleting a SignalR client. Does the current structure allow this scenario? Thank you very much!

**Comment by jalilverdiyev** [comment]
Hi! Yes, you can definitely try to replace the database with a much more simple system. Instead of repositories you can create a `Dictionary<Guid, Message>` and there you can keep all your messages. Just make sure that Dictionary is a static property or field in order to make the messages persistent while application is running but keep in mind that when you restart the application or stop it the messages will be deleted. If you don't want that, you can try to save messages to files via either `JsonSerialization` or `XmlSerialization`

**Comment by jalilverdiyev** [comment]
If you have any other questions I will be glad to answer;)

**Comment by borioan** [comment]
Hi! Thank you very, very much for your very fast response!!! 
I'm a very newbie in this area with SignalR, and I'm trying to get an idea of ​​how all these new features are connected. If I'm not asking too much, I think it would be useful for others to understand basic authentication concepts. In this idea, maybe in the future a version without using a database can be added to the current project. For example, I use SignalR in a scenario in the local LAN network, in which I have a server defined as a console app and several clients that are WPF. I don't use the application on the internet, the clients are only local, part of the local LAN network, but still some checks are needed, maybe the server is connected to the internet although I want to use it strictly internally - the clients must be part only to the local LAN. All I want is a simple authentication of the clients with the server and possibly minimal security settings. I searched all over the internet and I didn't find anything in this regard.

**Comment by jalilverdiyev** [comment]
You are welcome! I see, but implementing authentication in SignalR is a kind of messy thing;). The easy way that you can implement authentication, I guess is for each request you can ask for a specific token(or maybe just a secret code) and try to authenticate based on that. You can even try to implement JWT as authentication method where you can issue tokens and then in SignalR you can validate based on that. You can also refer to these two videos:
- https://www.youtube.com/watch?v=8g34hhmiI_Q -> This guy is a WPF pro;)
- https://www.youtube.com/watch?v=mrCxfifTepU

**Comment by borioan** [comment]
:-) 
I've been following these two guys for a few days. But I don't think I need such a sophisticated authentication system, what your application offers is enough for me at the moment, only that it shouldn't be based on a database but, as you suggested, on a Dictionary<Guid, Message> eventually serialized. An additional version would help me, which besides the current one would deal with a dictionary not with a database. One of the main problems I had with SignalR is that every time I started the computers (server and client), at the first connection, the client could not connect to the server. In your project version, I solved this first problem by implementing IHost directly in the App.xaml.cs constructor. Now the client connects automatically without problems!! Thank you very much! The next step is to solve a simple authentication. I would appreciate a new WPF project, in addition to the current solution, that deals with the approach using a dictionary and not a database. My best regards!

**Comment by jalilverdiyev** [comment]
Wow! I am glad that I helped someone with my project. Currently, I don't have enough time to prepare such a project but I will keep it in mind because I am going to need such a solution, if I find something interesting I will share it with you. For now, if you don't have any other questions I will close this issue, if you have don't hesitate to ask.
